//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sales
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Tbl_Customer Tbl_Customer { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
        public virtual Tbl_Staff Tbl_Staff { get; set; }
    }
}
